server:
  port: 8088
  
spring:
  datasource:
    url: jdbc:mysql://10.94.44.97:3306/wl_ov_app_conncar?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: 123456
    username: admin
      

